//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elite.CRM.Plugins.UkPostalCodeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://postcodesoftware.co.uk/", ConfigurationName="UkPostalCodeService.LookupSoap")]
    public interface LookupSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postcodesoftware.co.uk/getAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Elite.CRM.Plugins.UkPostalCodeService.Address getAddress(string account, string password, string postcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postcodesoftware.co.uk/getAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<Elite.CRM.Plugins.UkPostalCodeService.Address> getAddressAsync(string account, string password, string postcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postcodesoftware.co.uk/getGeoData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Elite.CRM.Plugins.UkPostalCodeService.GeoData getGeoData(string account, string password, string postcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postcodesoftware.co.uk/getGeoData", ReplyAction="*")]
        System.Threading.Tasks.Task<Elite.CRM.Plugins.UkPostalCodeService.GeoData> getGeoDataAsync(string account, string password, string postcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postcodesoftware.co.uk/getCredits", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Elite.CRM.Plugins.UkPostalCodeService.Account getCredits(string account, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postcodesoftware.co.uk/getCredits", ReplyAction="*")]
        System.Threading.Tasks.Task<Elite.CRM.Plugins.UkPostalCodeService.Account> getCreditsAsync(string account, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://postcodesoftware.co.uk/")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string address4Field;
        
        private string townField;
        
        private string countyField;
        
        private string postcodeField;
        
        private string premiseDataField;
        
        private short errorNumberField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
                this.RaisePropertyChanged("Address3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address4 {
            get {
                return this.address4Field;
            }
            set {
                this.address4Field = value;
                this.RaisePropertyChanged("Address4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
                this.RaisePropertyChanged("Town");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
                this.RaisePropertyChanged("County");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PremiseData {
            get {
                return this.premiseDataField;
            }
            set {
                this.premiseDataField = value;
                this.RaisePropertyChanged("PremiseData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public short ErrorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("ErrorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://postcodesoftware.co.uk/")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pAFBalanceField;
        
        private string pAFExpireField;
        
        private string pOSTZONBalanceField;
        
        private string pOSTZONExpireField;
        
        private short errorNumberField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PAFBalance {
            get {
                return this.pAFBalanceField;
            }
            set {
                this.pAFBalanceField = value;
                this.RaisePropertyChanged("PAFBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PAFExpire {
            get {
                return this.pAFExpireField;
            }
            set {
                this.pAFExpireField = value;
                this.RaisePropertyChanged("PAFExpire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string POSTZONBalance {
            get {
                return this.pOSTZONBalanceField;
            }
            set {
                this.pOSTZONBalanceField = value;
                this.RaisePropertyChanged("POSTZONBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string POSTZONExpire {
            get {
                return this.pOSTZONExpireField;
            }
            set {
                this.pOSTZONExpireField = value;
                this.RaisePropertyChanged("POSTZONExpire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public short ErrorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("ErrorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://postcodesoftware.co.uk/")]
    public partial class GeoData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string longitudeField;
        
        private string latitudeField;
        
        private string eastingField;
        
        private string northingField;
        
        private string postcodeField;
        
        private short errorNumberField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Easting {
            get {
                return this.eastingField;
            }
            set {
                this.eastingField = value;
                this.RaisePropertyChanged("Easting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Northing {
            get {
                return this.northingField;
            }
            set {
                this.northingField = value;
                this.RaisePropertyChanged("Northing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
                this.RaisePropertyChanged("Postcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public short ErrorNumber {
            get {
                return this.errorNumberField;
            }
            set {
                this.errorNumberField = value;
                this.RaisePropertyChanged("ErrorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LookupSoapChannel : Elite.CRM.Plugins.UkPostalCodeService.LookupSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LookupSoapClient : System.ServiceModel.ClientBase<Elite.CRM.Plugins.UkPostalCodeService.LookupSoap>, Elite.CRM.Plugins.UkPostalCodeService.LookupSoap {
        
        public LookupSoapClient() {
        }
        
        public LookupSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LookupSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Elite.CRM.Plugins.UkPostalCodeService.Address getAddress(string account, string password, string postcode) {
            return base.Channel.getAddress(account, password, postcode);
        }
        
        public System.Threading.Tasks.Task<Elite.CRM.Plugins.UkPostalCodeService.Address> getAddressAsync(string account, string password, string postcode) {
            return base.Channel.getAddressAsync(account, password, postcode);
        }
        
        public Elite.CRM.Plugins.UkPostalCodeService.GeoData getGeoData(string account, string password, string postcode) {
            return base.Channel.getGeoData(account, password, postcode);
        }
        
        public System.Threading.Tasks.Task<Elite.CRM.Plugins.UkPostalCodeService.GeoData> getGeoDataAsync(string account, string password, string postcode) {
            return base.Channel.getGeoDataAsync(account, password, postcode);
        }
        
        public Elite.CRM.Plugins.UkPostalCodeService.Account getCredits(string account, string password) {
            return base.Channel.getCredits(account, password);
        }
        
        public System.Threading.Tasks.Task<Elite.CRM.Plugins.UkPostalCodeService.Account> getCreditsAsync(string account, string password) {
            return base.Channel.getCreditsAsync(account, password);
        }
    }
}
